[project]
name = "dnd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk>=1.28.1",
    "chromadb>=1.0.0",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "datamodel-code-generator>=0.83.0",
    "pypdf>=6.9.2",
    "ruff>=0.16.9",
]
