# generated by datamodel-codegen:
#   filename:  action.schema.json

from __future__ import annotations

from pydantic import BaseModel

from . import dice_schema, source_schema


class JsonSchemaForDD5ECreatureAction(BaseModel):
    name: str
    description: str
    attack_bonus: int | None = 0
    damage_dice: dice_schema.JsonSchemaForDice | None = None
    damage_bonus: int | None = 0
    legendary: bool | None = 'false'
    reaction: bool | None = 'false'
    source: source_schema.Model | None = None
