# generated by datamodel-codegen:
#   filename:  Character.schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from . import (
    Class_schema,
    Race_schema,
    Spell_schema,
    equipment_schema,
    feat_schema,
    source_schema,
    weapon_schema,
)
from .Creature_schema import DD5ECreature


class Player(BaseModel):
    name: str
    id: Annotated[
        str | None, Field(description="Wizards' DCI or other identifier.")
    ] = None


class Details(BaseModel):
    age: Annotated[int | None, Field(ge=0)] = None
    eyes: str | None = None
    hair: str | None = None
    skin: str | None = None
    weight: Annotated[int | None, Field(ge=0)] = None
    height: str | None = None
    personality: str | None = None
    ideal: str | None = None
    bond: str | None = None
    flaw: str | None = None
    backstory: str | None = None
    physical: str | None = None


class Treasure(BaseModel):
    pp: Annotated[float | None, Field(description='Platimum')] = 0
    ep: Annotated[float | None, Field(description='Electrum')] = 0
    gp: Annotated[float | None, Field(description='Gold')] = 0
    sp: Annotated[float | None, Field(description='Silver')] = 0
    cp: Annotated[float | None, Field(description='Copper')] = 0


class Background(BaseModel):
    name: str
    option: str | None = None
    description: str | None = None
    source: source_schema.Model | None = None


class DD5ECharacter(DD5ECreature):
    nickname: str | None = None
    player: Player
    xp: Annotated[int | None, Field(ge=0)] = 0
    race: Race_schema.DD5ERace
    classes: list[Class_schema.DD5EClass] | None = None
    background: Background | None = None
    details: Details | None = None
    weapon_proficiencies: list[str] | None = None
    armor_proficiencies: list[str] | None = None
    tool_proficiencies: list[str] | None = None
    feats: list[feat_schema.JsonSchemaForDD5EFeat] | None = None
    spells: list[Spell_schema.Model] | None = None
    weapons: list[weapon_schema.JsonSchemaForDD5EWeapon] | None = None
    equipment: list[equipment_schema.JsonSchemaForDD5EEquiment] | None = None
    treasure: Treasure | None = None
