# generated by datamodel-codegen:
#   filename:  Class.schema.json

from __future__ import annotations

from enum import IntEnum, StrEnum

from pydantic import BaseModel, conint

from . import feature_schema, source_schema


class HitDie(IntEnum):
    integer_1 = 1
    integer_2 = 2
    integer_4 = 4
    integer_6 = 6
    integer_8 = 8
    integer_10 = 10
    integer_12 = 12
    integer_20 = 20


class Spellcasting(StrEnum):
    field_ = ""
    str = "str"
    dex = "dex"
    con = "con"
    int = "int"
    wis = "wis"
    cha = "cha"


class DD5EClass(BaseModel):
    name: str
    level: conint(ge=1)
    subtype: str | None = None
    hit_die: HitDie | None = None
    spellcasting: Spellcasting | None = ""
    features: list[feature_schema.JsonSchemaForDD5EFeature] | None = None
    source: source_schema.Model | None = None
