# generated by datamodel-codegen:
#   filename:  conditions.schema.json

from __future__ import annotations

from enum import StrEnum


class JsonSchemaForDD5EConditions(StrEnum):
    Blinded = "Blinded"
    Charmed = "Charmed"
    Deafened = "Deafened"
    Exhaustion = "Exhaustion"
    Frightened = "Frightened"
    Grappled = "Grappled"
    Incapacitated = "Incapacitated"
    Invisible = "Invisible"
    Necrotic = "Necrotic"
    Paralyzed = "Paralyzed"
    Petrified = "Petrified"
    Poisoned = "Poisoned"
    Prone = "Prone"
    Restrained = "Restrained"
    Stunned = "Stunned"
    Unconscious = "Unconscious"
