# generated by datamodel-codegen:
#   filename:  Creature.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, conint

from . import (
    conditions_schema,
    damage_type_schema,
    dice_schema,
    image_schema,
    senses_schema,
    source_schema,
)


class Speed(BaseModel):
    Walk: int | None = 0
    Burrow: int | bool | None = False
    Climb: int | bool | None = 0
    Fly: int | bool | None = False
    Hover: bool | None = False
    Swim: int | bool | None = 0


class Skills(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Athletics: bool | int | None = False
    Acrobatics: bool | int | None = False
    SleightOfHand: bool | int | None = False
    Stealth: bool | int | None = False
    Arcana: bool | int | None = False
    History: bool | int | None = False
    Investigation: bool | int | None = False
    Nature: bool | int | None = False
    Religion: bool | int | None = False
    AnimalHandling: bool | int | None = False
    Insight: bool | int | None = False
    Medicine: bool | int | None = False
    Perception: bool | int | None = False
    Survival: bool | int | None = False
    Deception: bool | int | None = False
    Intimidation: bool | int | None = False
    Performance: bool | int | None = False
    Persuasion: bool | int | None = False


class AbilityScores(BaseModel):
    str: conint(ge=0) = Field(..., description='Strength')
    dex: conint(ge=0) = Field(..., description='Dexterty')
    con: conint(ge=0) = Field(..., description='Constitution')
    int: conint(ge=0) = Field(..., description='Intelligence')
    wis: conint(ge=0) = Field(..., description='Wisdom')
    cha: conint(ge=0) = Field(..., description='Charisma')


class SavingThrows(BaseModel):
    str: bool | int | None = False
    dex: bool | int | None = False
    con: bool | int | None = False
    int_: bool | int | None = Field(False, alias='int')
    wis: bool | int | None = False
    cha: bool | int | None = False


class ArmorClass(BaseModel):
    value: conint(ge=0) | None = 10
    description: str | None = 'Unarmored'


class Conditions(BaseModel):
    Blinded: bool | None = False
    Charmed: bool | None = False
    Deafened: bool | None = False
    Exhaustion: bool | None = False
    Frightened: bool | None = False
    Grappled: bool | None = False
    Incapacitated: bool | None = False
    Invisible: bool | None = False
    Necrotic: bool | None = False
    Paralyzed: bool | None = False
    Petrified: bool | None = False
    Poisoned: bool | None = False
    Prone: bool | None = False
    Restrained: bool | None = False
    Stunned: bool | None = False
    Unconscious: bool | None = False


class HitPoints(BaseModel):
    max: int | None = 0
    current: int | None = None
    temporary: int | None = None
    dice: list[dice_schema.JsonSchemaForDice] | None = None
    description: str | None = None


class DD5ECreature(BaseModel):
    name: str
    alignment: str | None = None
    speed: Speed = Field(..., description='Speed in feet')
    hit_points: HitPoints
    inspiration: str | None = None
    skills: Skills | None = None
    languages: list[str] | None = None
    ability_scores: AbilityScores
    saving_throws: SavingThrows | None = None
    senses: senses_schema.JsonSchemaForDD5ESenses | None = None
    description: str | None = None
    armor_class: ArmorClass
    shield: bool | None = Field(False, description='Toggle if shield is being used.')
    conditions: Conditions | None = None
    condition_immunities: list[conditions_schema.JsonSchemaForDD5EConditions] | None = (
        None
    )
    damage_immunities: list[damage_type_schema.JsonSchemaForDD5EDamageType] | None = (
        None
    )
    damage_resistances: list[damage_type_schema.JsonSchemaForDD5EDamageType] | None = (
        None
    )
    damage_vulnerabilities: (
        list[damage_type_schema.JsonSchemaForDD5EDamageType] | None
    ) = None
    image: image_schema.JsonSchemaForImages | None = None
    source: source_schema.Model | None = None
