# generated by datamodel-codegen:
#   filename:  damage_type.schema.json

from __future__ import annotations

from pydantic import Field, RootModel


class JsonSchemaForDD5EDamageType(RootModel[str]):
    root: str = Field(
        'none',
        description='This schema describes a string value of a Damage Type.',
        examples=[
            'none',
            'Piercing',
            'Slashing',
            'Bludgeoning',
            'Acid',
            'Cold',
            'Fire',
            'Force',
            'Lightning',
            'Necrotic',
            'Poison',
            'Psychic',
            'Radiant',
            'Thunder',
        ],
        title='JSON Schema for D&D 5e Damage Type.',
    )
