# generated by datamodel-codegen:
#   filename:  dice.schema.json

from __future__ import annotations

from enum import IntEnum

from pydantic import BaseModel, conint


class Sides(IntEnum):
    integer_1 = 1
    integer_4 = 4
    integer_6 = 6
    integer_8 = 8
    integer_10 = 10
    integer_12 = 12
    integer_20 = 20
    integer_100 = 100


class JsonSchemaForDice(BaseModel):
    sides: Sides | None = 4
    count: conint(ge=1, le=60) | None = 1
    mod: int | None = 0
