# generated by datamodel-codegen:
#   filename:  equipment.schema.json

from __future__ import annotations

from .item_schema import JsonSchemaForDD5EPhysicalItem


class JsonSchemaForDD5EEquiment(JsonSchemaForDD5EPhysicalItem):
    quantity: int | None = 0
