# generated by datamodel-codegen:
#   filename:  feature.schema.json

from __future__ import annotations

from pydantic import BaseModel

from . import source_schema


class JsonSchemaForDD5EFeature(BaseModel):
    name: str
    description: str | None = None
    source: source_schema.Model | None = None
