# generated by datamodel-codegen:
#   filename:  image.schema.json

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, Field

from . import source_schema


class JsonSchemaForImages(BaseModel):
    uri: AnyUrl | None = None
    alt: str = Field(
        ...,
        description='The text to display if image cannot load. `alt` should describe the image generally.',
    )
    caption: str | None = Field(
        None, description='The text to display below the image.'
    )
    source: source_schema.Model | None = None
