# generated by datamodel-codegen:
#   filename:  item.schema.json

from __future__ import annotations

from pydantic import BaseModel

from . import source_schema


class JsonSchemaForDD5EPhysicalItem(BaseModel):
    name: str
    weight: float | None = 0
    description: str | None = None
    magic: bool | None = False
    source: source_schema.Model | None = None
