# generated by datamodel-codegen:
#   filename:  senses.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class JsonSchemaForDD5ESenses(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Blindsight: bool | str | None = Field(
        False, description="`false` or provide Blindsight trait text."
    )
    Darkvision: bool | str | None = Field(
        False, description="`false` or provide Darkvision trait text."
    )
    Tremorsense: bool | str | None = Field(
        False, description="`false` or provide Tremorsense trait text."
    )
    Truesight: bool | str | None = Field(
        False, description="`false` or provide Truesight trait text."
    )
