# generated by datamodel-codegen:
#   filename:  senses.schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class JsonSchemaForDD5ESenses(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Blindsight: Annotated[
        bool | str | None,
        Field(description="`false` or provide Blindsight trait text."),
    ] = False
    Darkvision: Annotated[
        bool | str | None,
        Field(description="`false` or provide Darkvision trait text."),
    ] = False
    Tremorsense: Annotated[
        bool | str | None,
        Field(description="`false` or provide Tremorsense trait text."),
    ] = False
    Truesight: Annotated[
        bool | str | None, Field(description="`false` or provide Truesight trait text.")
    ] = False
