# generated by datamodel-codegen:
#   filename:  Spell.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, Field

from . import source_schema, tag_schema


class Component(StrEnum):
    V = 'V'
    S = 'S'
    M = 'M'
    F = 'F'
    DF = 'DF'
    XP = 'XP'


class Model(BaseModel):
    name: str = Field(..., examples=['Acid Splash'])
    description: str
    higher_level: str | None = None
    level: str = Field(..., examples=['Cantrip', '1', '2', '3', '4'])
    casting_time: str
    range_area: str = Field(..., examples=['60ft', 'Self'])
    components: list[Component]
    material: str | None = None
    ritual: bool | None = 'false'
    concentration: bool | None = 'false'
    duration: str = Field(..., examples=['Instantaneous'])
    school: str | None = Field(None, examples=['Conjuring'])
    attack_save: str | None = Field(None, examples=['DEX Save', 'Ranged'])
    damage_effect: str | None = Field(None, examples=['Acid'])
    tags: tag_schema.Model | None = Field(None, examples=['Bard', 'Wizard', 'Warlock'])
    source: source_schema.Model | None = None
