# generated by datamodel-codegen:
#   filename:  tag.schema.json

from __future__ import annotations

from pydantic import Field, RootModel


class Model(RootModel[list[str]]):
    root: list[str] = Field(..., description='This schema describes a generic tag.')
