# generated by datamodel-codegen:
#   filename:  tag.schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class Model(RootModel[list[str]]):
    root: Annotated[
        list[str], Field(description="This schema describes a generic tag.")
    ]
