# generated by datamodel-codegen:
#   filename:  weapon.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from . import damage_type_schema, dice_schema
from .item_schema import JsonSchemaForDD5EPhysicalItem


class Damage(BaseModel):
    dice: dice_schema.JsonSchemaForDice | None = None
    type: damage_type_schema.JsonSchemaForDD5EDamageType | None = Field(
        'none', validate_default=True
    )


class VersatileDamage(BaseModel):
    dice: dice_schema.JsonSchemaForDice | None = None


class Range(BaseModel):
    normal: int | None = 5
    long: int | None = 0


class ThrowRange(BaseModel):
    normal: int | None = 0
    long: int | None = 0


class Properties(BaseModel):
    Ammunition: str | None = ''
    Finesse: bool | None = False
    Heavy: bool | None = False
    Light: bool | None = False
    Loading: bool | None = False
    Monk: bool | None = False
    Reach: bool | None = False
    Thrown: bool | None = False
    TwoHanded: bool | None = False
    Versatile: bool | None = False


class JsonSchemaForDD5EWeapon(JsonSchemaForDD5EPhysicalItem):
    category: str | None = ''
    damage: Damage
    versatile_damage: VersatileDamage | None = None
    range: Range | None = None
    throw_range: ThrowRange | None = None
    properties: Properties | None = None
    equipped: bool | None = False
